---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    name: catalogue
    app: catalogue
    framework: go
spec:
  replicas: 1
  selector:
    matchLabels:
      name: catalogue
  template:
    metadata:
      labels:
        name: catalogue
        app: catalogue
        version: v1
        framework: go
    spec:
      containers:
      - name: catalogue
        {{- if .Values.catalogue }}
        {{- if .Values.catalogue.version }}
        image: {{.Values.kubernetes.repository}}:catalogue-{{.Values.catalogue.version}}
        {{- else }}
        image: {{.Values.kubernetes.repository}}:catalogue
        {{- end}}
        {{- else }}
        image: {{.Values.kubernetes.repository}}:catalogue
        {{- end}}
        imagePullPolicy: {{ .Values.kubernetes.imagePullPolicy }}
        env:
          - name: APPD_APPNAME
            value: {{.Values.appd.APPD_APPNAME}}
          - name: APPD_TIERNAME
            value: {{.Values.catalogue.APPD_TIERNAME}}
          # - name: APPD_NODENAME
          #   value: {{.Values.appd.APPD_NODENAME}}
          - name: APPD_CONTROLLER_HOST
            value: {{.Values.appd.APPD_CONTROLLER_HOST}}
          - name: APPD_CONTROLLER_PORT
            value: {{ quote .Values.appd.APPD_CONTROLLER_PORT}}
          - name: APPD_CONTROLLER_USE_SSL
            value: {{ quote .Values.appd.APPD_CONTROLLER_USE_SSL}}
          - name: APPD_CONTROLLER_ACCOUNT
            value: {{.Values.appd.APPD_CONTROLLER_ACCOUNT}}
          - name: APPD_CONTROLLER_ACCESS_KEY
            value: {{.Values.appd.APPD_CONTROLLER_ACCESS_KEY}}
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: {{ .Values.kubernetes.readOnlyRootFilesystem }}
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 3
