{{- if .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: socks-ingress
  annotations:
    # kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   more_set_headers "X-Xss-Protection: 1; mode=block always;";
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.frontend.ingress.url }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: front-end
            port:
              number: 80
{{- end }}
