---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    name: shipping
    app: shipping
    framework: java
spec:
  replicas: 1
  selector:
    matchLabels:
      name: shipping
  template:
    metadata:
      labels:
        name: shipping
        app: shipping
        version: v1
        framework: java
    spec:
      containers:
      - name: shipping
        {{- if .Values.shipping }}
        {{- if .Values.shipping.version }}
        image: {{.Values.kubernetes.repository}}:shipping-{{.Values.shipping.version}}
        {{- else }}
        image: {{.Values.kubernetes.repository}}:shipping
        {{- end }}
        {{- else }}
        image: {{.Values.kubernetes.repository}}:shipping
        {{- end }}
        imagePullPolicy: {{ .Values.kubernetes.imagePullPolicy }}
        env:
         - name: JAVA_OPTS
           value: {{ .Values.java.options }}
        resources:
          limits:
            cpu: 900m
            memory: 6000Mi
          requests:
            cpu: 300m
            memory: 2000Mi
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: {{ .Values.kubernetes.readOnlyRootFilesystem }}
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 900
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 3
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
