---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    name: user
    app: user
    framework: go
spec:
  replicas: 1
  selector:
    matchLabels:
      name: user
  template:
    metadata:
      labels:
        name: user
        app: user
        version: v1
        framework: go
    spec:
      containers:
      - name: user
        {{- if .Values.user }}
        {{- if .Values.user.version }}
        image: {{.Values.kubernetes.repository}}:user-{{.Values.user.version}}
        {{- else }}
        image: {{.Values.kubernetes.repository}}:user
        {{- end }}
        {{- else }}
        image: {{.Values.kubernetes.repository}}:user
        {{- end }}
        imagePullPolicy: {{ .Values.kubernetes.imagePullPolicy }}
        resources:
          limits:
            cpu: 300m
            memory: 1200Mi
          requests:
            cpu: 100m
            memory: 400Mi
        ports:
        - containerPort: 8084
        env:
        - name: MONGO_HOST
          value: user-db:27017
        - name: APPD_APPNAME
          value: {{.Values.appd.APPD_APPNAME}}
        - name: APPD_TIERNAME
          value: {{.Values.user.APPD_TIERNAME}}
        # - name: APPD_NODENAME
        #   value: {{.Values.appd.APPD_NODENAME}}
        - name: APPD_CONTROLLER_HOST
          value: {{.Values.appd.APPD_CONTROLLER_HOST}}
        - name: APPD_CONTROLLER_PORT
          value: {{ quote .Values.appd.APPD_CONTROLLER_PORT}}
        - name: APPD_CONTROLLER_USE_SSL
          value: {{ quote .Values.appd.APPD_CONTROLLER_USE_SSL}}
        - name: APPD_CONTROLLER_ACCOUNT
          value: {{.Values.appd.APPD_CONTROLLER_ACCOUNT}}
        - name: APPD_CONTROLLER_ACCESS_KEY
          value: {{.Values.appd.APPD_CONTROLLER_ACCESS_KEY}}
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: {{ .Values.kubernetes.readOnlyRootFilesystem }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8084
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8084
          initialDelaySeconds: 180
          periodSeconds: 3
